# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Password')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='User Name')),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('first_name', models.CharField(max_length=250, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, null=True, verbose_name='Last Name')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date of Birthday')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=250, null=True, verbose_name='Country')),
                ('about', models.TextField(null=True, verbose_name='About User')),
                ('status', models.BooleanField(default=True, verbose_name='Activate')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=250, null=True, verbose_name='Gendor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('profile', models.ImageField(default='default/user.jpg', upload_to=users.models.path_and_rename)),
                ('language', models.ManyToManyField(db_table='related_users_language', to='language.Language')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.IntegerField(default=0, verbose_name='Bussiness Type')),
                ('vendor', models.CharField(max_length=250, null=True, verbose_name='Vendor ID')),
                ('website', models.CharField(max_length=250, null=True, verbose_name='Website')),
                ('youtube', models.CharField(max_length=250, null=True, verbose_name='Youtube')),
                ('commission', models.CharField(max_length=250, null=True, verbose_name='Individual Commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
    ]
