# Generated by Django 4.0 on 2021-12-28 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='User Name')),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('first_name', models.CharField(max_length=250, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=250, null=True, verbose_name='Last Name')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date of Birthday')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=250, null=True, verbose_name='Country')),
                ('about', models.TextField(null=True, verbose_name='About User')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other'), ('4', 'Prefer Not To Say')], max_length=250, null=True, verbose_name='Gendor')),
                ('profile', models.ImageField(default='default/user.jpg', upload_to='users')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
