# Generated by Django 4.0 on 2022-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='business_status',
            field=models.BooleanField(default=False, verbose_name='Bussiness Status'),
        ),
    ]
