# Generated by Django 4.0 on 2022-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('gyms', '0001_initial'),
        ('users', '0003_users_language_business'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Businesses',
        ),
    ]
