# Generated by Django 4.0 on 2022-01-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_business_businesses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesses',
            table='businesses',
        ),
    ]
