# Generated by Django 4.0 on 2022-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_businesses_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
    ]
