# Generated by Django 4.0 on 2022-01-05 05:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_options_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=250, null=True, verbose_name='Gendor'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(default='default/user.jpg', upload_to=users.models.path_and_rename),
        ),
    ]
