# Generated by Django 4.0 on 2022-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_gender_alter_users_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='business_type',
            field=models.IntegerField(default=0, verbose_name='Bussiness Type'),
        ),
    ]
