# Generated by Django 4.0 on 2022-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_title_alter_language_flag'),
        ('users', '0009_alter_businesses_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.ManyToManyField(db_table='related_users_language', to='language.Language'),
        ),
    ]
