# Generated by Django 4.0 on 2021-12-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('language', '0002_language_title_alter_language_flag'),
        ('users', '0003_users_language_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Category Name')),
                ('image', models.ImageField(default='default/trainer_category.jpg', upload_to='trainer/category')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'db_table': 'trainer_category',
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=250, null=True, verbose_name='Certification Year')),
                ('logo', models.ImageField(default='default/trainer_logo.jpg', upload_to='trainers/logo')),
                ('banner', models.ManyToManyField(db_table='related_trainers_banner', null=True, to='masters.Banner')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('category', models.ManyToManyField(db_table='related_trainers_category', null=True, to='trainers.Trainer_Category')),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='Trainers_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=250, verbose_name='Bank Account Number')),
                ('swift_code', models.CharField(max_length=250, verbose_name='Swift Code')),
                ('account_holder_name', models.CharField(max_length=250, verbose_name='Account Holder Name')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers')),
            ],
            options={
                'db_table': 'trainer_bank',
            },
        ),
    ]
