# Generated by Django 4.0 on 2022-01-07 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trainers.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_At'),
        ),
        migrations.AddField(
            model_name='trainer_category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trainer_category',
            name='image',
            field=models.ImageField(default='default/trainer_category.jpg', upload_to=trainers.models.category_logo_path),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='logo',
            field=models.ImageField(default='default/trainer_logo.jpg', upload_to=trainers.models.trainer_logo_path),
        ),
        migrations.AlterField(
            model_name='trainers_bank',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers'),
        ),
    ]
