# Generated by Django 4.0 on 2022-01-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_remove_language_langauge'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.language'),
        ),
    ]
