# Generated by Django 4.0 on 2022-01-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_feature_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
