# Generated by Django 4.0 on 2021-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('action', models.CharField(max_length=250, verbose_name='Action')),
                ('constants', models.CharField(max_length=250, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'db_table': 'email_template',
            },
        ),
        migrations.CreateModel(
            name='System_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=250, verbose_name='Page')),
                ('logo', models.ImageField(default='default/system_image.jpg', upload_to='system_image', verbose_name='Logo')),
            ],
            options={
                'db_table': 'system_image',
            },
        ),
    ]
