# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('subject', models.CharField(max_length=250, null=True, verbose_name='Subject')),
                ('action', models.CharField(max_length=250, null=True, verbose_name='Action')),
                ('constants', models.CharField(max_length=250, null=True, verbose_name='Subject')),
                ('body', models.TextField(null=True, verbose_name='Body')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'db_table': 'email_template',
            },
        ),
        migrations.CreateModel(
            name='System_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=250, verbose_name='Page')),
                ('image', models.ImageField(default='default/system_image.jpg', upload_to='system_image', verbose_name='Image')),
            ],
            options={
                'db_table': 'system_image',
            },
        ),
    ]
