# Generated by Django 4.0 on 2022-01-10 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
