# Generated by Django 4.0 on 2022-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_managements', '0002_email_template_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_template',
            name='action',
            field=models.CharField(max_length=250, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='body',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='constants',
            field=models.CharField(max_length=250, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='subject',
            field=models.CharField(max_length=250, null=True, verbose_name='Subject'),
        ),
    ]
