# Generated by Django 4.0 on 2022-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_managements', '0003_alter_email_template_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_image',
            name='logo',
        ),
        migrations.AddField(
            model_name='system_image',
            name='image',
            field=models.ImageField(default='default/system_image.jpg', upload_to='system_image', verbose_name='Image'),
        ),
    ]
