# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('flag', models.ImageField(default='default/flag.jpg', upload_to='language/flags', verbose_name='Flag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
