# Generated by Django 4.0 on 2021-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(default='default/flag.jpg', upload_to='language/flags', verbose_name='Flag'),
        ),
    ]
