# Generated by Django 4.0 on 2022-01-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_title_alter_language_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='langauge',
        ),
    ]
