# Generated by Django 4.0 on 2022-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('gyms', '0002_alter_gym_bank_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_subscription',
            name='description',
            field=models.ManyToManyField(db_table='related_subscription_description', to='gyms.Gym_Description'),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='banner',
            field=models.ManyToManyField(db_table='related_gyms_banner', to='masters.Banner'),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='category',
            field=models.ManyToManyField(db_table='related_gyms_category', to='gyms.Gym_Category'),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='feature',
            field=models.ManyToManyField(db_table='related_gyms_feature', to='masters.Feature'),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='review',
            field=models.ManyToManyField(db_table='related_gyms_review', to='gyms.Gym_Review'),
        ),
        migrations.AlterField(
            model_name='gyms',
            name='subscription',
            field=models.ManyToManyField(db_table='related_gyms_subscription', to='gyms.Gym_Subscription'),
        ),
    ]
