# Generated by Django 4.0 on 2021-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('bank_account', models.FloatField()),
                ('bank_swift_code', models.FloatField()),
                ('account_holder_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'setting_bank',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('contact_map', models.CharField(max_length=250)),
                ('contact_address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'setting_contact',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('time_out', models.CharField(max_length=250)),
                ('client', models.FloatField()),
                ('port', models.FloatField()),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'setting_email',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_format', models.DateTimeField()),
                ('date_formate', models.DateTimeField()),
                ('records_per_page', models.IntegerField(default=0)),
                ('record_views', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'setting_reading',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=250)),
                ('inquiry_email', models.CharField(max_length=250)),
                ('names_in_email', models.CharField(max_length=250)),
                ('site_email', models.CharField(max_length=250)),
                ('copyright_text', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'setting_site',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(max_length=250)),
                ('twitter_url', models.CharField(max_length=250)),
                ('instagram_url', models.CharField(max_length=250)),
                ('youtube_url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'setting_social',
            },
        ),
    ]
