# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250, null=True)),
                ('bank_account', models.FloatField(null=True)),
                ('bank_swift_code', models.FloatField(null=True)),
                ('account_holder_name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'setting_bank',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('contact_map', models.CharField(max_length=250, null=True)),
                ('contact_address', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'setting_contact',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250, null=True)),
                ('time_out', models.CharField(max_length=250, null=True)),
                ('client', models.FloatField(null=True)),
                ('port', models.FloatField(null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'setting_email',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_format', models.CharField(default='DD/MM/YYYY HH:MM:SS A', max_length=250, null=True)),
                ('date_format', models.CharField(default='DD/MM/YYYY HH:MM:SS A', max_length=250, null=True)),
                ('records_per_page', models.IntegerField(default=0, null=True)),
                ('record_views', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'setting_reading',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=250, null=True)),
                ('inquiry_email', models.CharField(max_length=250, null=True)),
                ('names_in_email', models.CharField(max_length=250, null=True)),
                ('site_email', models.CharField(max_length=250, null=True)),
                ('copyright_text', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'setting_site',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(max_length=250, null=True)),
                ('twitter_url', models.CharField(max_length=250, null=True)),
                ('instagram_url', models.CharField(max_length=250, null=True)),
                ('youtube_url', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'setting_social',
            },
        ),
    ]
