# Generated by Django 4.0 on 2022-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_holder_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_account',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_swift_code',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_map',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='host',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='port',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='time_out',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='date_formate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='date_time_format',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='record_views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='records_per_page',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='copyright_text',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='inquiry_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='names_in_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
