# Generated by Django 4.0 on 2022-01-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='date_formate',
            new_name='date_format',
        ),
    ]
