# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When')),
                ('where', models.CharField(max_length=250, verbose_name='Where')),
                ('field', models.CharField(max_length=250, verbose_name='What')),
                ('origin', models.CharField(max_length=250, verbose_name='From')),
                ('update', models.CharField(max_length=250, verbose_name='To')),
                ('user', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
