# Generated by Django 4.0 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=250, verbose_name='Gym User Name')),
                ('order_id', models.CharField(max_length=250, verbose_name='Order ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Phone')),
                ('start_at', models.DateField(verbose_name='Start Date')),
                ('end_at', models.DateField(verbose_name='End Date')),
                ('plan_type', models.CharField(max_length=250, verbose_name='Plan Type')),
                ('plan_price', models.FloatField(default=0, verbose_name='Plan Price')),
                ('gym_commission', models.FloatField(default=0, verbose_name='Gym Commission')),
                ('admin_commission', models.FloatField(default=0, verbose_name='Admin Commission')),
                ('duration', models.IntegerField(verbose_name='Plan Duration')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
